apiVersion: skaffold/v2alpha3
kind: Config 
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nyoung125/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.js'
            dest: .
    - image: nyoung125/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: nyoung125/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: nyoung125/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: nyoung125/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: nyoung125/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .